### ISSUE TITLE
Generic version for 32/64 bit hash prospector.

### ISSUE THREAD

**Issue by gzm55** [skeeto/hash-prospector#8]
if do not use jit, the 32/64 bit prospector may be more easy to maintain.

**Comment by skeeto** [comment]
That's true, and a portable version would be structured like hp16.c with 
its dynamic switch dispatch (with added performance costs). However, the 
value of this project is its outputs rather than the code itself, so 
maintainability is a low priority. Note: the hillclimb tool does not JIT, 
and I've taken advantage of this to run it for long periods on a Raspi.

Until the Apple M1 just a few months ago, portability was not really an 
issue since anywhere you'd want to run this was already x86 and so 
supported by the JIT (even on Windows via WSL).
